server:
  port: 8888   # HTTP (Tomcat) port
spring:
  #ftp服务器的地址
  ftp:
    host: 119.29.107.83
    port: 21
    username: ftpuser
    password: xsg435268
    basepath: /home/ftpuser/www/images
    httpPath: http://119.29.107.83:8088/images
  servlet:
    multipart:
      enabled: true
      file-size-threshold: 0B
      location: #
      resolve-lazily: false
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://119.29.107.83:3307/tokentest?useUnicode=true&characterEncoding=utf-8&useTimezone=true&serverTimezone=GMT%2B8
    username: root
    password: root
    type: com.alibaba.druid.pool.DruidDataSource
    #最大活跃数
    maxActive: 20
    #初始化数量
    initialSize: 1
    #最大连接等待超时时间
    maxWait: 60000
    #打开PSCache，并且指定每个连接PSCache的大小
    poolPreparedStatements: true
    maxPoolPreparedStatementPerConnectionSize: 20
    #通过connectionProperties属性来打开mergeSql功能；慢SQL记录
    #connectionProperties: druid.stat.mergeSql=true;druid.stat.slowSqlMillis=5000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 1 from dual
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    #配置监控统计拦截的filters，去掉后监控界面sql将无法统计,'wall'用于防火墙
    filters: stat, wall, log4j

  main:
    allow-bean-definition-overriding: true #当遇到同样名字的时候，是否允许覆盖注册

  jpa:
    hibernate:
      ddl-auto: update  # 第一次建表create  后面用update
    show-sql: true
    open-in-view: true

    #添加那个目录的文件需要restart
#    spring.devtools.restart.additional-paths=src/main/java
    #排除那个目录的文件不需要restart
  devtools:
    restart:
      additional-exclude: src/main/java
#    spring.devtools.restart.exclude=static/**,public/**
#禁止thymeleaf缓存（建议：开发环境设置为false，生成环境设置为true）
#  spring.thymeleaf.cache=false